version: '3.4'

services:
  proffesionalbackendsetup:
    image: proffesionalbackendsetup
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
